title:              Novit.ai
email:              info@novit.ai
description:        Real and actionable industry insights from global machine learning
author:             Novit.ai
baseurl:            ""
url:                "https://novitai-website.github.io"

# Social Profiles
twitter_username:
github_username:
facebook_username:
linkedin_username:  novitai

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-srcset
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

srcset:
  cache: "/tmp/images"

collections:
  positions:
    output: true
  investigations:
    output: true

future: true
